trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'
    - script: |
        dotnet build --configuration $(buildConfiguration)
      displayName: 'Build Project'

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: Test
    displayName: 'Run Unit Tests'
    steps:
    - script: |
        dotnet test --configuration $(buildConfiguration)
      displayName: 'Run Tests'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure'
    steps:
    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'prog8860-service-connection'
        appType: 'functionApp'
        appName: 'prog8860-lab4-app'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'